### ISSUE TITLE
CLI fails on version 0.1.0-alpha.12 with "designsystemet: command not found"

### ISSUE THREAD

**Issue by unekinn** [digdir/designsystemet#2163]
### Description of the bug

When trying to run the CLI command, it fails. This started happening with 0.1.0-alpha.12. It seems to be a different bug than the one described in https://github.com/digdir/designsystemet/issues/2133.

### Steps To Reproduce

1. Run `npx @digdir/designsystemet@0.1.0-alpha.12`
2. See error `designsystemet: command not found`
3. Run `npx @digdir/designsystemet@0.1.0-alpha.11`
4. See expected output

The problem also happens when `@digdir/designsystemet` is a dependency in package.json and run through e.g. a script
```json
    "build": "npm run clean && designsystemet tokens -o ./dist",
```

### Additional Information

In case it's relevant:
OS is macOS 14.5
npm version 10.8.1
node version 20.12.1

**Comment by mimarz** [comment]
Jepp! 

It broke after we changed transpiler to better support using the package in code (in addition to the cli).

We changed to use [tsup](https://github.com/egoist/tsup) and it seemingly worked before, but not now 🤔

**Comment by mimarz** [comment]
Should be working albeit with a warning as I had to add `assert { type:'json' }` to the `package.json` import in the `init` script.

**Comment by Hifoz** [comment]
Hi, it looks like this is still broken in the latest version. I tried with both 0.1.0-alpha.18 and 0.1.0-next.20, and I'm getting `sh: designsystemet: command not found` with both of these

**Comment by mimarz** [comment]
> Hi, it looks like this is still broken in the latest version. I tried with both 0.1.0-alpha.18 and 0.1.0-next.20, and I'm getting `sh: designsystemet: command not found` with both of these

Ah! Thanks for the headsup. It was broken at some point since I am doing som summer cleaning and changing our release managment, but `@next` should be working (`@digdir/designsystemet@0.1.0-next.20`).

How are you running the cli, with npx or installed locally?

**Comment by Hifoz** [comment]
I've tried it with npx and locally installed, but both do fail. And I'm running on linux

**Comment by Hifoz** [comment]
> Interesting! Do you have time for a call tomorrow (or some time this week) to look closer at this together?

Yeah, sure! I'm in the designsystemet-slack, so you should find me there.

**Comment by mimarz** [comment]
This error is due to misunderstanding of [publishConfig](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#publishconfig).
